name: CI

on:
  pull_request: branches:[main]

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/nest-mycv
  VERSION: ${{ github.sha }}
  COMPOSE_FILE: docker-compose.yml

jobs:
  build:
    runs-on: ubuntu-latest
    setps:
      #Checkout the code
      - name: Checkout code
      - uses: actions/checkout@v3

      #Set up Docker buildx
      - name: Set up Docker buildx
      - uses: docker/setup-buildx-action@v1

      #Login Github container registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
